name: cherry_toast
description: A new way to display toasts in flutter with elegant design and animations
version: 1.11.0
homepage: 'https://github.com/koukibadr/Cherry-Toast'
funding:
- 'https://www.buymeacoffee.com/koukibadr'
screenshots:
- description: Cherry Toast pacakge front image.
  path: example/package_frontimage.png
environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=1.17.0'
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
flutter: null
